# ******** Mend Unified CLI Template for Github Actions ********
#
# You may wish to alter this file to override the build tool and Mend scanning technologies.
#
# For more configuration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/integrations/page/scan_with_the_mend_cli.html
#
# ******** Description ********
# mend dep will automatically use package managers and file system scanning to detect open source components.
# mend code will automatically detect languages and frameworks used in your projects to scan for code weaknesses.

# If you are NOT using a service user, and have multiple organizations, don't forget to call the scope -s parameter to set the organization

name: Mend CLI Scan

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install node modules
      run: npm install --only=prod --ignore-scripts
    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.MEND_SCA_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_SCA_USERKEY}}
        MEND_URL: https://saas.mend.io
      run: |
        echo "Downloading Mend CLI"
        curl curl https://downloads.mend.io/cli/darwin_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        echo "run Mend dependencies (SCA) scan"
        mend dep -u